# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'system_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1600, 950)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1800, 1200))
        font = QtGui.QFont()
        font.setFamily("宋体")
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ICON/window2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title_lab_name = QtWidgets.QLabel(self.centralwidget)
        self.label_title_lab_name.setGeometry(QtCore.QRect(0, 0, 300, 100))
        self.label_title_lab_name.setText("")
        self.label_title_lab_name.setPixmap(QtGui.QPixmap("ICON/labname.jpg"))
        self.label_title_lab_name.setScaledContents(True)
        self.label_title_lab_name.setOpenExternalLinks(False)
        self.label_title_lab_name.setObjectName("label_title_lab_name")
        self.label_title_name = QtWidgets.QLabel(self.centralwidget)
        self.label_title_name.setGeometry(QtCore.QRect(480, -10, 681, 100))
        self.label_title_name.setText("")
        self.label_title_name.setPixmap(QtGui.QPixmap("ICON/title_name.jpg"))
        self.label_title_name.setScaledContents(False)
        self.label_title_name.setObjectName("label_title_name")
        self.label_bit_icon = QtWidgets.QLabel(self.centralwidget)
        self.label_bit_icon.setGeometry(QtCore.QRect(1470, 0, 100, 100))
        self.label_bit_icon.setText("")
        self.label_bit_icon.setPixmap(QtGui.QPixmap("ICON/BIT.jpg"))
        self.label_bit_icon.setScaledContents(True)
        self.label_bit_icon.setObjectName("label_bit_icon")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(1220, 850, 351, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_select_font = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_select_font.setEnabled(True)
        self.pushButton_select_font.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton_select_font.setMaximumSize(QtCore.QSize(100, 50))
        self.pushButton_select_font.setObjectName("pushButton_select_font")
        self.horizontalLayout.addWidget(self.pushButton_select_font)
        self.pushButton_init_system = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_init_system.setEnabled(True)
        self.pushButton_init_system.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton_init_system.setMaximumSize(QtCore.QSize(100, 50))
        self.pushButton_init_system.setObjectName("pushButton_init_system")
        self.horizontalLayout.addWidget(self.pushButton_init_system)
        self.pushButton_system_exit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_system_exit.setEnabled(True)
        self.pushButton_system_exit.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton_system_exit.setMaximumSize(QtCore.QSize(100, 50))
        self.pushButton_system_exit.setObjectName("pushButton_system_exit")
        self.horizontalLayout.addWidget(self.pushButton_system_exit)
        self.label_rebuild_hyper_image = QtWidgets.QLabel(self.centralwidget)
        self.label_rebuild_hyper_image.setGeometry(QtCore.QRect(550, 170, 500, 500))
        self.label_rebuild_hyper_image.setMinimumSize(QtCore.QSize(200, 200))
        self.label_rebuild_hyper_image.setMaximumSize(QtCore.QSize(500, 500))
        self.label_rebuild_hyper_image.setText("")
        self.label_rebuild_hyper_image.setPixmap(QtGui.QPixmap("ICON/label_rebuild_hyperimage.jpg"))
        self.label_rebuild_hyper_image.setScaledContents(True)
        self.label_rebuild_hyper_image.setObjectName("label_rebuild_hyper_image")
        self.label_show_spectral_curve = QtWidgets.QLabel(self.centralwidget)
        self.label_show_spectral_curve.setGeometry(QtCore.QRect(1070, 170, 500, 500))
        self.label_show_spectral_curve.setMinimumSize(QtCore.QSize(200, 200))
        self.label_show_spectral_curve.setMaximumSize(QtCore.QSize(500, 500))
        self.label_show_spectral_curve.setText("")
        self.label_show_spectral_curve.setPixmap(QtGui.QPixmap("ICON/label_spectral_curve.jpg"))
        self.label_show_spectral_curve.setScaledContents(True)
        self.label_show_spectral_curve.setObjectName("label_show_spectral_curve")
        self.label_origin_image_icon = QtWidgets.QLabel(self.centralwidget)
        self.label_origin_image_icon.setGeometry(QtCore.QRect(20, 170, 500, 500))
        self.label_origin_image_icon.setMinimumSize(QtCore.QSize(200, 200))
        self.label_origin_image_icon.setMaximumSize(QtCore.QSize(600, 600))
        self.label_origin_image_icon.setText("")
        self.label_origin_image_icon.setPixmap(QtGui.QPixmap("ICON/label_origin_image_icon.jpg"))
        self.label_origin_image_icon.setScaledContents(True)
        self.label_origin_image_icon.setObjectName("label_origin_image_icon")
        self.label_text_name_right = QtWidgets.QPushButton(self.centralwidget)
        self.label_text_name_right.setGeometry(QtCore.QRect(600, 690, 400, 100))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        self.label_text_name_right.setFont(font)
        self.label_text_name_right.setObjectName("label_text_name_right")
        self.label_text_conf_right = QtWidgets.QPushButton(self.centralwidget)
        self.label_text_conf_right.setGeometry(QtCore.QRect(1130, 690, 400, 100))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        self.label_text_conf_right.setFont(font)
        self.label_text_conf_right.setObjectName("label_text_conf_right")
        self.widget_select_face_object = QtWidgets.QTabWidget(self.centralwidget)
        self.widget_select_face_object.setGeometry(QtCore.QRect(20, 830, 561, 91))
        self.widget_select_face_object.setObjectName("widget_select_face_object")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(130, 0, 423, 52))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.gridLayoutWidget_2.setFont(font)
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_button_right = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_button_right.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_button_right.setObjectName("gridLayout_button_right")
        self.pushButton_collect_face_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_collect_face_2.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton_collect_face_2.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.pushButton_collect_face_2.setFont(font)
        self.pushButton_collect_face_2.setObjectName("pushButton_collect_face_2")
        self.gridLayout_button_right.addWidget(self.pushButton_collect_face_2, 0, 4, 1, 1)
        self.pushButton_start_recognition_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_start_recognition_2.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton_start_recognition_2.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.pushButton_start_recognition_2.setFont(font)
        self.pushButton_start_recognition_2.setObjectName("pushButton_start_recognition_2")
        self.gridLayout_button_right.addWidget(self.pushButton_start_recognition_2, 0, 5, 1, 1)
        self.pushButton_select_face_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_select_face_2.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton_select_face_2.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.pushButton_select_face_2.setFont(font)
        self.pushButton_select_face_2.setObjectName("pushButton_select_face_2")
        self.gridLayout_button_right.addWidget(self.pushButton_select_face_2, 0, 3, 1, 1)
        self.pushButton_open_camera_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_open_camera_2.setEnabled(True)
        self.pushButton_open_camera_2.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton_open_camera_2.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.pushButton_open_camera_2.setFont(font)
        self.pushButton_open_camera_2.setObjectName("pushButton_open_camera_2")
        self.gridLayout_button_right.addWidget(self.pushButton_open_camera_2, 0, 1, 1, 1)
        self.widget_select_face_object.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 423, 52))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.gridLayoutWidget_3.setFont(font)
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_button_right_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_button_right_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_button_right_2.setObjectName("gridLayout_button_right_2")
        self.pushButton_collect_hyperspectral = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_collect_hyperspectral.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton_collect_hyperspectral.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.pushButton_collect_hyperspectral.setFont(font)
        self.pushButton_collect_hyperspectral.setObjectName("pushButton_collect_hyperspectral")
        self.gridLayout_button_right_2.addWidget(self.pushButton_collect_hyperspectral, 0, 3, 1, 1)
        self.pushButton_show_spectral_curve = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_show_spectral_curve.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton_show_spectral_curve.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.pushButton_show_spectral_curve.setFont(font)
        self.pushButton_show_spectral_curve.setObjectName("pushButton_show_spectral_curve")
        self.gridLayout_button_right_2.addWidget(self.pushButton_show_spectral_curve, 0, 2, 1, 1)
        self.combo_select_face_object = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.combo_select_face_object.setMinimumSize(QtCore.QSize(50, 50))
        self.combo_select_face_object.setMaximumSize(QtCore.QSize(200, 50))
        self.combo_select_face_object.setObjectName("combo_select_face_object")
        self.combo_select_face_object.addItem("")
        self.combo_select_face_object.addItem("")
        self.gridLayout_button_right_2.addWidget(self.combo_select_face_object, 0, 0, 1, 1)
        self.line_edit_get_texture_text = QtWidgets.QLineEdit(self.tab_2)
        self.line_edit_get_texture_text.setGeometry(QtCore.QRect(430, 0, 113, 50))
        self.line_edit_get_texture_text.setMinimumSize(QtCore.QSize(100, 50))
        self.line_edit_get_texture_text.setMaximumSize(QtCore.QSize(500, 50))
        self.line_edit_get_texture_text.setText("")
        self.line_edit_get_texture_text.setObjectName("line_edit_get_texture_text")
        self.widget_select_face_object.addTab(self.tab_2, "")
        self.label_rgb_show_state_back = QtWidgets.QLabel(self.centralwidget)
        self.label_rgb_show_state_back.setGeometry(QtCore.QRect(10, 110, 1591, 701))
        self.label_rgb_show_state_back.setText("")
        self.label_rgb_show_state_back.setPixmap(QtGui.QPixmap("ICON/label_mono_show_state_back_new1.jpg"))
        self.label_rgb_show_state_back.setScaledContents(True)
        self.label_rgb_show_state_back.setObjectName("label_rgb_show_state_back")
        self.label_rgb_show_state_back.raise_()
        self.label_title_lab_name.raise_()
        self.label_title_name.raise_()
        self.label_bit_icon.raise_()
        self.horizontalLayoutWidget.raise_()
        self.label_rebuild_hyper_image.raise_()
        self.label_show_spectral_curve.raise_()
        self.label_text_name_right.raise_()
        self.label_text_conf_right.raise_()
        self.widget_select_face_object.raise_()
        self.label_origin_image_icon.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.widget_select_face_object.setCurrentIndex(0)
        self.pushButton_select_font.clicked.connect(MainWindow.select_font)
        self.pushButton_init_system.clicked.connect(MainWindow.init_system)
        self.pushButton_system_exit.clicked.connect(MainWindow.system_exit)
        self.pushButton_open_camera_2.clicked.connect(MainWindow.open_camera_2)
        self.pushButton_select_face_2.clicked.connect(MainWindow.select_face_2)
        self.pushButton_collect_face_2.clicked.connect(MainWindow.collect_face_2)
        self.pushButton_start_recognition_2.clicked.connect(MainWindow.start_recognition_2)
        self.pushButton_show_spectral_curve.clicked.connect(MainWindow.choice_show_spectral_curve)
        self.pushButton_collect_hyperspectral.clicked.connect(MainWindow.collect_hyperspectral_image)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "高光谱智能识别系统"))
        self.pushButton_select_font.setText(_translate("MainWindow", "字体"))
        self.pushButton_init_system.setText(_translate("MainWindow", "重置系统"))
        self.pushButton_system_exit.setText(_translate("MainWindow", "退出"))
        self.label_text_name_right.setText(_translate("MainWindow", "名称_材质"))
        self.label_text_conf_right.setText(_translate("MainWindow", "置信度"))
        self.pushButton_collect_face_2.setText(_translate("MainWindow", "采集人脸2"))
        self.pushButton_start_recognition_2.setText(_translate("MainWindow", "开始识别2"))
        self.pushButton_select_face_2.setText(_translate("MainWindow", "选择人脸2"))
        self.pushButton_open_camera_2.setText(_translate("MainWindow", "打开相机2"))
        self.widget_select_face_object.setTabText(self.widget_select_face_object.indexOf(self.tab), _translate("MainWindow", "基本"))
        self.pushButton_collect_hyperspectral.setText(_translate("MainWindow", "采集高光谱图像"))
        self.pushButton_show_spectral_curve.setText(_translate("MainWindow", "显示光谱曲线"))
        self.combo_select_face_object.setCurrentText(_translate("MainWindow", "object"))
        self.combo_select_face_object.setItemText(0, _translate("MainWindow", "object"))
        self.combo_select_face_object.setItemText(1, _translate("MainWindow", "face"))
        self.widget_select_face_object.setTabText(self.widget_select_face_object.indexOf(self.tab_2), _translate("MainWindow", "拓展"))

